<?php
/**
 * @file
 * Code for the Commerce EU VAT FI feature.
 */

/**
 * Impliments hook_commerce_vat_country_info_alter().
 */
function commerce_eu_vat_fi_commerce_vat_country_info_alter(&$vat_countries) {
  $vat_countries['FI']['default_field'] = TRUE;
}

/**
 * Implements hook_commerce_vat_rate_info().
 */
function commerce_eu_vat_fi_commerce_vat_rate_info() {
  $items = array(
    'fi_reduced' => array(
      'country' => 'FI',
      'eu' => TRUE,
      'title' => t('FI Reduced'),
      'rates' => array(
        '09_2010' => array(
          'name' => '09_2010',
          'rate' => .09,
          'start' => '20100701'
        ),
      ),
    ),

    'fi_intermediate' => array(
      'country' => 'FI',
      'eu' => TRUE,
      'title' => t('FI Intermediate'),
      'rates' => array(
        '13_2010' => array(
          'name' => '13_2010',
          'rate' => .13,
          'start' => '20100701'
        ),
      ),
    ),

    'fi_standard' => array(
      'country' => 'FI',
      'eu' => TRUE,
      'title' => t('FI Standard'),
      'rates' => array(
        '23_2010' => array(
          'name' => '23_2010',
          'rate' => .23,
          'start' => '20100701'
        ),
      ),
    ),

  );

  return $items;
}
